# Generated by Django 3.2.9 on 2021-11-02 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=45)),
                ('adresa', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Clienti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=45)),
                ('prenume', models.CharField(max_length=45)),
                ('adresa', models.CharField(max_length=45)),
                ('data_nasterii', models.DateTimeField()),
                ('salariu', models.FloatField()),
                ('functie', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Asociere_Imprumuturi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_imprumut', models.DateTimeField()),
                ('termen_scadent', models.DateTimeField()),
                ('dobanda', models.IntegerField()),
                ('suma', models.FloatField()),
                ('id_banca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.banci')),
                ('id_clienti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clienti')),
            ],
        ),
    ]
