# Generated by Django 3.2.9 on 2021-11-04 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asociere_imprumuturi',
            name='id_banca',
        ),
        migrations.RemoveField(
            model_name='asociere_imprumuturi',
            name='id_clienti',
        ),
        migrations.AddField(
            model_name='asociere_imprumuturi',
            name='banci',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.banci'),
        ),
        migrations.AddField(
            model_name='asociere_imprumuturi',
            name='clienti',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clienti'),
        ),
        migrations.AlterField(
            model_name='asociere_imprumuturi',
            name='data_imprumut',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='asociere_imprumuturi',
            name='dobanda',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='asociere_imprumuturi',
            name='suma',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='asociere_imprumuturi',
            name='termen_scadent',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='banci',
            name='adresa',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='banci',
            name='nume',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='clienti',
            name='adresa',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='clienti',
            name='data_nasterii',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='clienti',
            name='functie',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='clienti',
            name='nume',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='clienti',
            name='prenume',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='clienti',
            name='salariu',
            field=models.FloatField(null=True),
        ),
    ]
